import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
}

android {
    namespace = "com.termfold.app"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.termfold.app"
        minSdk = 26
        // Pinned to 28 deliberately. Android only lets an app execute binaries from its own
        // nativeLibraryDir/data directory when the app targets API 28 or lower; at 29+ the process
        // runs in the untrusted_app domain and execve is denied outright. This is exactly why
        // Termux itself pins targetSdk=28. Without it the bundled PRoot cannot start at all.
        targetSdk = 28
        versionCode = 4
        versionName = "1.3"
    }

    androidResources {
        localeFilters += listOf("en")
    }

    /**
     * Signing for the release build.
     *
     * The key is generated by `tools/make-keystore.ps1` and is deliberately not in source control.
     * When it is absent the release build is left unsigned rather than failing, so a checkout
     * without the key can still compile.
     */
    signingConfigs {
        create("release") {
            // Credentials come from local.properties (never committed) or the environment, so
            // the public repository carries no secrets:
            //   termfold.storePassword=...   / TERMFOLD_STORE_PASSWORD
            //   termfold.keyPassword=...     / TERMFOLD_KEY_PASSWORD
            val local = Properties()
            rootProject.file("local.properties").takeIf { it.isFile }?.inputStream()?.use { stream -> local.load(stream) }
            fun secret(key: String, env: String): String? =
                local.getProperty(key) ?: System.getenv(env)

            val keystore = rootProject.file("termfold-release.jks")
            val storePass = secret("termfold.storePassword", "TERMFOLD_STORE_PASSWORD")
            if (keystore.isFile && storePass != null) {
                storeFile = keystore
                storePassword = storePass
                keyAlias = "termfold"
                keyPassword = secret("termfold.keyPassword", "TERMFOLD_KEY_PASSWORD") ?: storePass
            }
        }
    }

    buildTypes {
        debug {
            isMinifyEnabled = false
        }
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            signingConfigs.getByName("release").takeIf { it.storeFile != null }?.let { signingConfig = it }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        }
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    lint {
        // `targetSdk` is pinned to 28 on purpose: Android only permits an app to execute binaries
        // from its own storage at API 28 or lower. Raising it would break the bundled Linux
        // environment entirely, so this check is a false positive for this app rather than a
        // warning worth acting on.
        disable += "ExpiredTargetSdkVersion"
    }

    // Output APKs carry the app's name rather than the module's: "TermFold-release.apk" instead
    // of "app-release.apk".
    applicationVariants.all {
        outputs.all {
            (this as com.android.build.gradle.internal.api.BaseVariantOutputImpl)
                .outputFileName = "TermFold-${name}.apk"
        }
    }

    // Bundled executables ship as lib*.so and are extracted so the OS places them in
    // nativeLibraryDir, the one location this app's SELinux domain may execute from.
    androidResources {
        // Executables must stay uncompressed so the loader can map them directly, and the Ubuntu
        // image must stay byte-identical or its gzip stream is no longer valid. `.bin` is a
        // deliberately neutral extension: AGP transparently gunzips assets ending in `.gz`, which
        // would silently change the bytes this app ships.
        noCompress += listOf("so", "bin")
    }

    packaging {
        jniLibs {
            // Forces the native libraries to be extracted to disk at install time. With the
            // modern default (`extractNativeLibs=false`) they stay inside the APK and cannot be
            // exec'd, which breaks PRoot and its loader.
            useLegacyPackaging = true
        }
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

dependencies {
    implementation("androidx.core:core-ktx:1.17.0")
    implementation("androidx.activity:activity-compose:1.10.1")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.9.4")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.9.4")

    implementation("androidx.compose.ui:ui:1.10.3")
    implementation("androidx.compose.foundation:foundation:1.10.3")
    implementation("androidx.compose.material3:material3:1.4.0")
    implementation("androidx.compose.runtime:runtime:1.10.3")

    // Termux's terminal emulator + view, prebuilt with libtermux.so (native PTY) for every ABI.
    // The emulator renders the screen and the view handles gestures, keys and the IME; the native
    // side forks the PTY and execs whatever command it is handed, which is what makes the session
    // a real terminal rather than a pipe.
    implementation("com.github.termux.termux-app:terminal-emulator:0.118.3")
    implementation("com.github.termux.termux-app:terminal-view:0.118.3")

    implementation("androidx.datastore:datastore-preferences:1.1.7")
    implementation("androidx.documentfile:documentfile:1.0.0")
    implementation("io.coil-kt:coil-compose:2.7.0")
    implementation("io.coil-kt:coil-svg:2.7.0")

    // The tar reader that unpacks the bundled rootfs is pure Kotlin with no Android
    // dependencies, so it is covered by a plain JVM test against the real Ubuntu image.
    testImplementation("junit:junit:4.13.2")

    // Bzip2 decompression for registry agents that ship .tar.bz2 archives (goose). Only the
    // bzip2 decoder is used — tar and zip parsing stay in the app's own pure-Kotlin reader.
    implementation("org.apache.commons:commons-compress:1.25.0")

    // A real org.json for the JVM tests, whose classpath otherwise only has the Android
    // stubs that throw on every call.
    testImplementation("org.json:json:20240303")
}

tasks.withType<Test>().configureEach {
    // The rootfs image is a build input, not a fixture checked into source control, so the test
    // that reads it is pointed at the same file the app ships.
    systemProperty(
        "termfold.rootfsAsset",
        layout.projectDirectory.file("src/main/assets/ubuntu-x86_64.bin").asFile.absolutePath,
    )
    // A local set of downloaded registry archives, when present, drives the AcpArchivesTest
    // against real agent downloads: -Dtermfold.acpArchives=<dir> on the gradle command line.
    System.getProperty("termfold.acpArchives")?.let {
        systemProperty("termfold.acpArchives", it)
    }
}
